repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Run ruff formatter
        entry: uvx ruff format
        language: system
        types: [python]
      - id: ruff-check
        name: Run ruff linter
        entry: uvx ruff check
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy-typecheck
        name: Run mypy type checker
        entry: uv run mypy .
        language: system
        types: [python]
        pass_filenames: false
      # - id: pytest
      #   name: Run pytest
      #   entry: uvx pytest
      #   language: system
      #   types: [python]
